# Informações do Site
title: LimasDev61 | Roadmap Python
description: Um roadmap de Python gratuito, feito de um estudante para outros estudantes
email: seu-email@exemplo.com # Opcional

# Configurações de Aparência
theme: jekyll-theme-cayman

# Configurações de Markdown
markdown: kramdown
highlighter: rouge

# Caminhos
baseurl: ""
url: "https://LimasDev61.github.io"