# Informações do Site
title: LimasDev61 | Roadmap Python
description: Repositório de códigos para estudantes de Python
email: seu-email@exemplo.com # Opcional

# Configurações de Aparência
theme: jekyll-theme-cayman

# Configurações de Markdown
markdown: kramdown
highlighter: rouge

# Caminhos
baseurl: ""
url: "https://LimasDev61.github.io"